language: python
cache: pip
python:
  - 3.6
services:
  - docker
  - mysql
  - redis-server
install:
  - pip install -r requirements.txt
script:
  - echo '=== unit tests ==='
  - python -m pytest -v
  - echo '=== test oshp scanner ==='
  - mysql -u root -e 'create database headers;'
  - mysql -u root --password="$MYSQL_PASSWORD" headers < conf/sql/headers.sql || exit 1
  - python cli.py scanner -f conf/develop.csv || exit 1
  - echo '=== test oshp web ==='
  - echo '=== build docker images ==='
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker image build -t oshp/secureheaders:$IMAGE_TAG -f docker/secureheaders/Dockerfile .
  - docker image build -t oshp/database:develop -f docker/database/Dockerfile .
  - docker image push oshp/secureheaders:$IMAGE_TAG
  - docker image push oshp/database:develop
env:
  global:
    - IMAGE_TAG=4.0.0
    - MYSQL_PASSWORD=''
    - REDIS_HOST=''
