language: python
python:
  - 3.6
services:
  - docker
stages:
  - build

script:
  - python -m pytest -v

jobs:
  include:
    - stage: "build"
      name: "Docker Image Deploy Images [Scanner/Database/Web] - STABLE"
    - before_script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - script:
      - docker image build -t oshp/secureheaders:$IMAGE_TAG -f docker/secureheaders/Dockerfile .
      - docker image build -t oshp/scanner:$IMAGE_TAG -f docker/secureheaders/Dockerfile .
      - docker image build -t oshp/database:develop -f docker/database/Dockerfile .
      - docker image push oshp/secureheaders:$IMAGE_TAG
      - docker image push oshp/scanner:$IMAGE_TAG
      - docker image push oshp/database:develop
      - docker image tag oshp/secureheaders:$IMAGE_TAG oshp/secureheaders:stable
      - docker image tag oshp/scanner:$IMAGE_TAG oshp/scanner:stable
      - docker image push oshp/secureheaders:stable
      - docker image push oshp/scanner:stable
      branches:
        only:
          - master
    - stage: "build"
      name: "Docker Image Deploy Images [Scanner/Database/Web] - UNSTABLE"
    - before_script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - script:
      - docker image build -t oshp/secureheaders:unstable -f docker/secureheaders/Dockerfile .
      - docker image build -t oshp/scanner:unstable -f docker/secureheaders/Dockerfile .
      - docker image build -t oshp/database:develop-unstable -f docker/database/Dockerfile .
      - docker image push oshp/secureheaders:unstable
      - docker image push oshp/scanner:unstable
      - docker image push oshp/database:develop-unstable
      branches:
        only:
          - /^[0-9].*rc[0-9]{2}$/

env:
  global:
    - IMAGE_TAG=4.0.0
