version: 0.0
os: linux
files:
  - source: /
    destination: /opt/headers
hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 120
      runas: ubuntu
  Install:
    - location: deploy/install_service.sh
      timeout: 120
      runas: ubuntu
  ApplicationStart:
    - location: deploy/start_service.sh
      timeout: 120
      runas: ubuntu
