version: '3'
services:
    mysqld:
        image: oshp/database:develop
        container_name: oshp-database
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: headers
          MYSQL_USER: mysql
          MYSQL_PASSWORD: password
    oshp:
        build:
          context: .
          dockerfile: ./docker/secureheaders/Dockerfile
          args:
            BRANCH: develop
        container_name: oshp-secureheaders
        depends_on:
          - mysqld
        labels:
          - traefik.enable=true
          - traefik.backend=oshp
          - traefik.port=5000
          - traefik.backend.loadbalancer.method=drr
          - traefik.frontend.rule=PathPrefix:/
    traefik:
        image: traefik:1.4
        container_name: oshp-lb
        command: --docker --docker.watch --docker.exposedbydefault=false --docker.domain=localhost --web --web.statistics --web.metrics
        ports:
          - 80:80
          - 8080:8080
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    redis:
        image: redis:4.0.1-alpine
        container_name: oshp-mdb
